export const keyMapping = {
  Feature_name: "Feature Name",
  attr1: "Gene expression level",
  attr2: "Gene expression variance",
  attr3: "Co-expression degree",
  attr4: "CAI",
  attr5: "Sequence variation",
  attr6: "Synthetic sick/lethal paralogs in S. cerevisiae",
  attr7: "Ortholog essentiality in S. cerevisiae",
  attr8: "Length",
  attr9: "Hits",
  attr10: "Reads",
  attr11: "Freedom index",
  attr12: "Neighborhood index",
  attr13: "Upstream hits 100",
  attr14: "GRACE (1: E; -1 NE)",
  attr15: "GRACEv2 (1: E; -1 NE)",
  attr16: "RF prediction(1:E, -1 NE)",
  attr17: "RF prediction score",
  ORF_ID: "ORF_ID",
  Common: "Common",
  Description: "Description",
};
